name: Close linked issues on PR merge

on:
  pull_request:
    types: [closed]

jobs:
  close_issues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Close linked issues
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body;
            const issueNumbers = Array.from(
              prBody.matchAll(/(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#(\d+)/gi),
              m => m[1]
            );
            
            for (const number of issueNumbers) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: Number(number),
                state: "closed"
              });
            }